application: delicious-sweeper
version: 1-0-7
runtime: python
api_version: 1

default_expiration: "1d"

skip_files:
- ^(.*/)?\.DS_Store
- ^(.git)

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /strings
  static_files: strings.xml
  upload: strings.xml

- url: /parse
  static_files: parse.html
  upload: parse.html

- url: /fetch
  script: api/fetch.py

- url: /login
  script: api/login.py

- url: /delete
  script: api/delete.py

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  mime_type: image/x-icon

- url: /js
  static_dir: js
  
- url: /img
  static_dir: img
  
- url: /css
  static_dir: css

- url: /.*
  static_files: 404.html
  upload: 404.html

error_handlers:
- file: errors/error.html
- error_code: dos_api_denial
  file: errors/error.html
- error_code: over_quota
  file: errors/over_quota.html
